version: '3'

services:
  dev:
    build:
      context: . 
      dockerfile: dockers/dev/Dockerfile 
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8080"
    volumes:
        - ./orders/:/home
    ports:
        - 8080:8080